### ISSUE TITLE
Production env monitoring - Install microsoft Clarity

### ISSUE THREAD

**Issue by douglara** [douglara/woofed-crm#100]
Como configurar identidade do usuário:
https://learn.microsoft.com/en-us/clarity/setup-and-installation/identify-api

**Comment by douglara** [comment]
@YukioArie 
Parece que a identificação do usuário não está rolando bem, vamos vendo como contornar

**Comment by YukioArie** [comment]
@douglara, dei uma olhada no meu pull request, e esqueci de colocar o script de identificação no layout do application. Porém eu coloquei nos outros layouts, q é o internal e o embeded. Talvez colocando no application possa funcionar. N consegui testar no ambiente de desenvolvimento tbm
