### ISSUE TITLE
Validate phone number

### ISSUE THREAD

**Issue by douglara** [douglara/woofed-crm#171]

**Comment by carl0xs** [comment]
Olá, 

Eu iria pegar essa issue para resolver, mas estava vendo aqui no projeto que já existe uma validação para o formato do número do usuário, tanto no frontend como no backend. Teria outro lugar para adicionar?

**Comment by YukioArie** [comment]
Olá @hsolrac, inicialmente resolvemos esse problema, mas esquecemos de fechar a issue. Agradecemos muito pela sua contribuição no Woofed!
