### ISSUE TITLE
Detalhes no contato

### ISSUE THREAD

**Issue by raphagamendes** [douglara/woofed-crm#243]
Ao clicar em contatos e selecionar o contato que voce quer ver o detalhe, ele retorna os detalhes do primeiro da lista, independente de qual contato voce quer ver os detalhes

**Comment by YukioArie** [comment]
@raphagamendes, estamos cientes desse bug, e devemos atualizar a branch principal com a correção até amanhã.
Obrigado pelo feedback 😃

**Comment by douglara** [comment]
Obrigado @raphagamendes feito a correção no PR: https://github.com/douglara/woofed-crm/pull/242
