### ISSUE TITLE
Contact custom attributes definitions display attribute_key and not attribute_display_name

### ISSUE THREAD

**Issue by YukioArie** [douglara/woofed-crm#263]
app/views/accounts/deals/details/_show_custom_attributes.html.erb
![image](https://github.com/douglara/woofed-crm/assets/45243355/aa4defcd-a603-4659-b907-e28551b8e839)
![image](https://github.com/douglara/woofed-crm/assets/45243355/8be622c7-7d17-4d5b-837a-c9ed94e08ff9)
![image](https://github.com/douglara/woofed-crm/assets/45243355/94ea4008-3991-454b-8d80-dcc3ceead14b)

**Comment by douglara** [comment]
Dar uam testada no método: `custom_attribute_display_name`
