### ISSUE TITLE
error: invalid path 'app/assets/images/pause-solid.svg:Zone.Identifier' fatal: unable to checkout working tree

### ISSUE THREAD

**Issue by inboundwebhub** [douglara/woofed-crm#317]
C:\Users\Sheth Siddh>git clone https://github.com/douglara/woofed-crm.git
Cloning into 'woofed-crm'...
remote: Enumerating objects: 14054, done.
remote: Counting objects: 100% (3581/3581), done.
remote: Compressing objects: 100% (879/879), done.
remote: Total 14054 (delta 2946), reused 2978 (delta 2664), pack-reused 10473
Receiving objects: 100% (14054/14054), 2.31 MiB | 7.22 MiB/s, done.
Resolving deltas: 100% (9197/9197), done.
error: invalid path 'app/assets/images/pause-solid.svg:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by YukioArie** [comment]
Hi @inboundwebhub! I fixed this bug in this commit 47e4bb0a1ae1cb3990ce428d0a204ea42ae08d2f, could u try to clone woofed again?
