### ISSUE TITLE
There is no instruction in the documentation how to get the Bearer Token

### ISSUE THREAD

**Issue by maldetect** [douglara/woofed-crm#324]
Hi Everyone,

I am trying to create an integration with woofed CRM but in the API documentation there ie no instruction how to get the Bearer Token

Can you guys guide me and update the documentation?

Thank you

**Comment by YukioArie** [comment]
Hi 😃 , we added a field to show the Bearer Token on edit user page. 

![Screenshot_29](https://github.com/douglara/woofed-crm/assets/45243355/2f8037bc-96aa-460e-a691-b446e05cf0a4)
