### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by sea-ads** [douglara/woofed-crm#349]
Hello, my name is Arthur, I'm new here, so I don't know if is the right place to post my suggestion.
A CRM needs to have the card price and the total cards amounts, in order to provide the comercial info. Without this, it's just a Trello pipe.
I have been using CRM for a while, and I'd like to help, if you wish, sharing some points of view.
How can I have your WhatsApp contact? 
Thanks.

**Comment by douglara** [comment]
Hello friend! Thanks for you suggestion, I would like to implement this feature and is on our map, follow updates on: https://github.com/users/douglara/projects/4/views/1?pane=issue&itemId=57851377
You can join us in Whatsapp Channel and Discord: https://docs.woofedcrm.com/docs/contents-resources 🖖
