### ISSUE TITLE
Can't assign a user to any account other than Account 1.

### ISSUE THREAD

**Issue by admdanielspalma** [douglara/woofed-crm#354]
I performed a fresh installation of the easy-install-latest image, and whenever I create users, they are always linked to the first account.

I cannot link them to any other account, making the additional accounts inaccessible.

I'm at motor_admin/data/accounts .

Thanks

**Comment by admdanielspalma** [comment]
https://github.com/douglara/woofed-crm/assets/75324578/f29a38c4-8253-44c3-b572-f2cf861391c4

Segue demonstração do bug

**Comment by douglara** [comment]
Hello @admdanielspalma, sorry we deprecated support for multi accounts because our team is small. I recommend to deploy a new instance ❤️
