### ISSUE TITLE
Problema de SSL self-hosted

### ISSUE THREAD

**Issue by rafabene** [douglara/woofed-crm#392]
Hello.

Tenho um chatwoot instalado em uma VPS com certificados válidos via Let's Encrypt.

Entretanto quando tento conectar o WoofedCRM com o Chatwoot eu recebo a seguinte mensagem de erro no console:

`Chatwoot connection error

<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=92.112.176.110:443 state=error: certificate verify failed (unable to get local issuer certificate)>>

TRANSACTION (0.3ms)  ROLLBACK`

Estou usando a tag docker :easyinstall-latest

Alguém poderia me dar uma luz, por favor?

**Comment by YukioArie** [comment]
Olá @rafabene! Esse problema está acontecendo nas imagens que tem o prefixo `easy-install`. Estamos cientes desse problema, e enquanto não corrigimos, use a imagem `latest` (docker pull douglara/woofedcrm:latest). Segue o link do dockerhub: https://hub.docker.com/r/douglara/woofedcrm/tags

**Comment by rafabene** [comment]
Obrigado.  Funcinou com a tag latest.  Vou manter an issue aberta para tracking e fix posterior.  Obrigado.

**Comment by YukioArie** [comment]
Corrigido.
Pull request https://github.com/douglara/woofed-crm/pull/426.
