### ISSUE TITLE
webhooks não funcionam na easy install latest

### ISSUE THREAD

**Issue by admdanielspalma** [douglara/woofed-crm#399]
Instalei hoje a easy install latest pelo docker e os webhooks não são disparados, bug?

**Comment by YukioArie** [comment]
Olá @admdanielspalma ! Esse problema está acontecendo nas imagens que tem o prefixo easy-install. Estamos cientes desse problema, e enquanto não corrigimos, use a imagem latest (docker pull douglara/woofedcrm:latest). Segue o link do dockerhub: https://hub.docker.com/r/douglara/woofedcrm/tags

**Comment by admdanielspalma** [comment]
Cara, tentei na latest e também não tão funcionando os webhooks.

**Comment by YukioArie** [comment]
Corrigido.
Pull request #426.
