### ISSUE TITLE
criação de novas contas não funciona na latest e na development-4e7abfdbe96fdf535cede6d2824bb55d058a2120

### ISSUE THREAD

**Issue by admdanielspalma** [douglara/woofed-crm#400]
Testei instalação zerada via docker da  development-4e7abfdbe96fdf535cede6d2824bb55d058a2120 e da latest e não funciona a criação de contas... ao clicar em criar conta dá erro.

Bug?

**Comment by YukioArie** [comment]
Esse erro acontece ao criar conta no motor admin, ou na pagina de login do woofed?

**Comment by admdanielspalma** [comment]
No sign up da tela inicial mesmo... pelo motor admin também não consegui mas não sei se tava fazendo direito, sou novo com a ferramenta

**Comment by YukioArie** [comment]
Testa com a imagem `latest`, link do dockerhub: https://hub.docker.com/r/douglara/woofedcrm

**Comment by admdanielspalma** [comment]
Testei com essa develpment e com a latest, falei ali em cima, só não ficou destacado o suficiente hehe

**Comment by admdanielspalma** [comment]
Não tem como criar conta... tu vai em create account e dá undefined local variable or method `site_url' for an instance of Account


tu vai em create user e não tem account... :(

**Comment by admdanielspalma** [comment]
Puts, agora foi erro meu, eu não tava usando o postgres vector, foi mal
