### ISSUE TITLE
GET Deal não funciona

### ISSUE THREAD

**Issue by admdanielspalma** [douglara/woofed-crm#404]
{{endpoint}}/api/v1/accounts/{{account_id}}/deals/58

Pessoal, se eu dou PUT, CREATE... a API funciona... mas se eu mudo pra GET dá erro.

É bug na versão atual? Tem algum jeito de eu conseguir usar? Obrigado!

**Comment by YukioArie** [comment]
Corrigido.
Pull request #424.
