### ISSUE TITLE
Não consigo ter mais de uma empresa/negocio

### ISSUE THREAD

**Issue by aliffstefano** [douglara/woofed-crm#417]
![image](https://github.com/user-attachments/assets/c84562c2-1bd8-4dfd-9d98-8423f4f12be2)
Antes de atualizar, conseguia usar deparado, no print tem DF Assessoria e Dyalog, agora todas as contas estão indo para a DF Assessoria, mesmo tentando trocar, ele mantem no #1

**Comment by YukioArie** [comment]
Olá @aliffstefano 
A funcionalidade de adicionar mais de uma empresa foi descontinuada, porém esta em nossos planos voltar com ela em forma de plugin.
Por ora, aconselho vc criar uma nova instalação para cada empresa.

**Comment by aliffstefano** [comment]
Assim @YukioArie, obrigado

**Comment by aliffstefano** [comment]
@YukioArie Só uma duvida a mais rsrs, consegue me dizer a ultima versão que ainda estava disponivel?
