### ISSUE TITLE
Redirect official site

### ISSUE THREAD

**Issue by leobaldoneto** [douglara/woofed-crm#7]
There is adware redirecting link clicks to pornographic sites.

https://woofedcrm.com/

**Comment by douglara** [comment]
Hi friend, yes is official site you can send more details about this problem?
To me it seems ok

**Comment by leobaldoneto** [comment]
Today it seems to be ok. It was redirectioning to some AD web sites when clicking on buttons.

**Comment by douglara** [comment]
I didn't do any changes but thanks for report, let me know if you notice anything strange, send some prints.
Thanks friend.

**Comment by douglara** [comment]
![woofed (2)](https://github.com/douglara/woofed-crm/assets/14988496/d9abf905-0336-4908-bfe8-cc4df6bf5b6a)

@bernardo140109 @vitor-assis  tested and confirmed this problem

**Comment by douglara** [comment]
Fixed, confirmed by @vitor-assis and @bernardo140109
